DECLARE
  V CENTROS.ID%TYPE;
BEGIN
  SELECT ID INTO V FROM CENTROS WHERE NOMBRE LIKE 'ABRERA';
  IF V>0 THEN
    DBMS_OUTPUT.PUT_LINE('ABRERA YA EXISTE');
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    INSERT INTO CENTROS (NOMBRE) VALUES('ABRERA');
    COMMIT;
END;
    
SELECT * FROM CENTROS;