DECLARE
  V CENTROS.ID%TYPE;
  P CENTROS.PROVINCIA%TYPE := 'ALAVA';
BEGIN
  SELECT ID INTO V FROM CENTROS WHERE NOMBRE LIKE 'ABRERA';
  UPDATE CENTROS SET PROVINCIA = P WHERE ID = V;
  IF SQL%FOUND THEN
    DBMS_OUTPUT.PUT_LINE('CENTRO ACTUALIZADO');
    COMMIT;
  ELSE
    DBMS_OUTPUT.PUT_LINE('NO EXISTE EL CENTRO');
  END IF;
END;

SELECT * FROM CENTROS;