--LOOP--

CREATE OR REPLACE PROCEDURE VER_TRABAJADOR IS
  CURSOR TRA_CURSOR IS
    SELECT APELLIDO1, FECHANAC
    FROM TRABAJADORES
    ORDER BY APELLIDO1;
  REG_TRABAJADOR TRA_CURSOR%ROWTYPE;
BEGIN
  OPEN TRA_CURSOR;
  LOOP
    FETCH TRA_CURSOR INTO REG_TRABAJADOR;
    DBMS_OUTPUT.PUT_LINE('EL TRABAJADOR DE APELLIDO ' || REG_TRABAJADOR.APELLIDO1 || ' NACIDO EL ' || REG_TRABAJADOR.FECHANAC);
    EXIT WHEN TRA_CURSOR%NOTFOUND;
  END LOOP;
  CLOSE TRA_CURSOR;
END;


--WHILE--

CREATE OR REPLACE PROCEDURE VER_TRABAJADOR IS
  CURSOR TRA_CURSOR IS
    SELECT APELLIDO1, NVL(TO_CHAR(FECHANAC), 'INEXISTENTE') AS FECHANAC
    FROM TRABAJADORES
    ORDER BY APELLIDO1;
  REG_TRABAJADOR TRA_CURSOR%ROWTYPE;
BEGIN
  OPEN TRA_CURSOR;
  FETCH TRA_CURSOR INTO REG_TRABAJADOR;
  IF TRA_CURSOR%NOTFOUND THEN
    DBMS_OUTPUT.PUT_LINE('LA TABLA TRABAJADORES ESTA VACIA');
  ELSE
    WHILE TRA_CURSOR%FOUND LOOP
      DBMS_OUTPUT.PUT_LINE('EL TRABAJADOR DE APELLIDO ' || REG_TRABAJADOR.APELLIDO1 || ' NACIDO EL ' || REG_TRABAJADOR.FECHANAC);
      FETCH TRA_CURSOR INTO REG_TRABAJADOR;
    END LOOP;
  END IF;
  CLOSE TRA_CURSOR;
END;


--FOR--

CREATE OR REPLACE PROCEDURE VER_TRABAJADOR IS
  CURSOR TRA_CURSOR IS
    SELECT APELLIDO1, NVL(TO_CHAR(FECHANAC), 'INEXISTENTE') AS FECHANAC
    FROM TRABAJADORES
    ORDER BY APELLIDO1;
BEGIN
  FOR REG IN TRA_CURSOR
    LOOP
      DBMS_OUTPUT.PUT_LINE('EL TRABAJADOR DE APELLIDO ' || REG.APELLIDO1 || ' NACIDO EL ' || REG.FECHANAC);
    END LOOP;
END;