DECLARE 
  V_ID CENTROS.ID%TYPE;
BEGIN
  SELECT ID INTO V_ID FROM CENTROS WHERE UPPER(NOMBRE) = 'ABRERA';
  DELETE FROM CENTROS WHERE ID = V_ID;
  IF SQL%FOUND THEN
    DBMS_OUTPUT.PUT_LINE('SE HA ELIMINADO EL CENTRO CON EL ID ' || V_ID);
    COMMIT;
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('NO SE HA ENCONTADO EL CENTRO CON EL NOMBRE ABRERA');
END;