DECLARE 
  V_ID CENTROS.ID%TYPE := 1;
  E_NOENCONTRADO EXCEPTION;
BEGIN
  DELETE FROM CENTROS WHERE ID = V_ID;
  IF SQL%FOUND THEN
    DBMS_OUTPUT.PUT_LINE('SE HA ELIMINADO EL CENTRO CON EL ID ' || V_ID || SQL%ROWCOUNT);
    COMMIT;
  ELSE
    RAISE E_NOENCONTRADO;
  END IF;
EXCEPTION
  WHEN E_NOENCONTRADO THEN
    RAISE_APPLICATION_ERROR(-20000, 'NO SE HA ENCONTRADO EL CENTRO CON EL ID 1');
END;

DESC CENTROS