--EJERCICIO 2--

SELECT E.CODIGOEMPLEADO AS "CODIGO DEL EMPLEADO", COUNT(C.CODIGOCLIENTE) AS "CLIENTES QUE ATIENDE"
FROM EMPLEADOS E, CLIENTES C
WHERE E.CODIGOEMPLEADO = C.CODIGOEMPLEADOREPVENTAS(+) 
AND UPPER(E.PUESTO) = 'REPRESENTANTE VENTAS'
GROUP BY E.CODIGOEMPLEADO
ORDER BY E.CODIGOEMPLEADO ASC;

--EJERCICIO 3--

SELECT NOMBRECLIENTE
FROM CLIENTES
WHERE CODIGOCLIENTE IN (SELECT CODIGOCLIENTE
                        FROM PEDIDOS
                        WHERE FECHAPEDIDO BETWEEN '2008-01-01' AND '2008-12-31');
                        
--EJERCICIO 4--

SELECT C.NOMBRECLIENTE, O.CIUDAD, O.LINEADIRECCION1||O.LINEADIRECCION2
FROM CLIENTES C, OFICINAS O
WHERE O.CIUDAD = C.CIUDAD
ORDER BY CIUDAD ASC;

--EJERCICIO 5--

SELECT C.NOMBRECLIENTE, P.CANTIDAD
FROM CLIENTES C, PAGOS P
WHERE C.CODIGOCLIENTE = P.CODIGOCLIENTE 
AND (P.CANTIDAD = (SELECT MAX(CANTIDAD) FROM PAGOS)
OR P.CANTIDAD = (SELECT MIN(CANTIDAD) FROM PAGOS));

--EJERCICIO 6--

ALTER TABLE EMPLEADOS
  ADD (SALARIO NUMBER(6),
      COMISION NUMBER(6) DEFAULT 0);
      
DESC EMPLEADOS;

SELECT * FROM EMPLEADOS;
             
CREATE OR REPLACE PROCEDURE MODIFICAREMPLEADOS 
IS
BEGIN
  UPDATE EMPLEADOS
  SET SALARIO = 1100
  WHERE UPPER(PUESTO) = 'SECRETARIA';
  UPDATE EMPLEADOS
  SET SALARIO = 1500
  WHERE UPPER(PUESTO) = 'DIRECTOR OFICINA';
  UPDATE EMPLEADOS
  SET SALARIO = 1800
  WHERE UPPER(PUESTO) IN ('SUBDIRECTOR MARKETING', 'SUBDIRECTOR VENTAS');
  UPDATE EMPLEADOS
  SET SALARIO = 1700
  WHERE UPPER(PUESTO) = 'REPRESENTANTE VENTAS';
  UPDATE EMPLEADOS
  SET SALARIO = 2200
  WHERE UPPER(PUESTO) = 'DIRECTOR GENERAL';
END;

EXECUTE MODIFICAREMPLEADOS;

SELECT * FROM EMPLEADOS;

--EJERCICIO 7--

CREATE OR REPLACE TRIGGER TRIGSALARIO 
BEFORE UPDATE OF SALARIO ON EMPLEADOS FOR EACH ROW
BEGIN
  IF :NEW.SALARIO > 3000 THEN
    UPDATE EMPLEADOS SET COMISION = 2;
  ELSE 
    UPDATE EMPLEADOS SET COMISION = 5;
  END IF;
END;
