DECLARE
  V VARCHAR2(15) := 'pepe';
BEGIN
  DBMS_OUTPUT.PUT_LINE('HOLA MUNDO' || ' ' || UPPER(V));
END;

DECLARE
  V CENTROS.ID%TYPE;
BEGIN
  SELECT MAX(ID) INTO V FROM CENTROS;
  IF V IS NULL THEN
    DBMS_OUTPUT.PUT_LINE('LA TABLA NO TIENE VALORES');
  ELSE
    DBMS_OUTPUT.PUT_LINE('EL ULTIMO IDENTIFICADOR DE CENTRO ES:' || ' ' || V);
  END IF;
END;