SET SERVEROUTPUT ON

DECLARE
  V VARCHAR2(15) := 'pepe';
BEGIN
  DBMS_OUTPUT.PUT_LINE('HOLA MUNDO' || ' ' || UPPER(V));
END;

DECLARE
  V CENTROS.NOMBRE%TYPE;
BEGIN
  SELECT NOMBRE INTO V FROM CENTROS;
  IF SQL%NOTFOUND THEN
    DBMS_OUTPUT.PUT_LINE('LA TABLA NO TIENE VALORES');
  ELSE
    DBMS_OUTPUT.PUT_LINE('EL ULTIMO IDENTIFICADOR DE CENTRO ES:' || ' ' || V);
  END IF;
EXCEPTION
      WHEN no_data_found THEN
        DBMS_OUTPUT.PUT_LINE('LA TABLA NO TIENE VALORES');
      WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR');
END;

SET SERVEROUTPUT ON

DECLARE
  V NUMBER;
BEGIN
  SELECT COUNT(ID) INTO V FROM CENTROS;
  IF V = 0 THEN
    DBMS_OUTPUT.PUT_LINE('LA TABLA ESTA VACIA');
  ELSE
    DBMS_OUTPUT.PUT_LINE('LA TABLA TIENE:' || ' ' || V || ' ' || 'VALORES');
  END IF;
END;

SELECT NOMBRE FROM CENTROS WHERE ID = 3;

EXECUTE VER_TRABAJADOR;
EXECUTE INSERT_CENTROS('BARCELONA', 'BARCELONA');